---
spring:
  web.resources.static-locations: "file:./app"
  config.activate.on-profile: default
  sql:
    init.mode: always
  datasource:
    url: "jdbc:sqlite:sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: always
    hikari:
      maximum-pool-size: 1
  logging:
    level:
      "[com.sap.cds.auditlog]": DEBUG
cds:
  dataSource:
    # url: "jdbc:sqlite:file:./sqlite.db?cache=shared"
    # driver-class-name: org.sqlite.JDBC
    csvInitializationMode: always
    csvFileSuffix: .csv
    embedded: true
  odata-v4.endpoint.path: "/api"
  # auditLog:
  #   v2.enabled: true
  # application:
  #   services: "ssm-srv"
# server:
#   port: 8080
# spring:
#   config.activate.on-profile: cloud
# logging:
#   level:
#     '[com.sap.cds.auditlog]': DEBUG
#   web.resources.static-locations: "file:./app"
#   jmx:
#     enabled: true
# cds:
#   datasource:
#     auto-config.enabled: false
#   odata-v4.endpoint.path: "/api"
#   security.mock.users:
#     - name: admin
#       password: admin
#       roles:
#       - admin
#       attributes:
#         businessPartner:
#         - "10401010"
#     - name: user
#       password: user
# server.servlet.encoding:
#   charset: UTF-8
#   force: true
# management:
#   endpoint:
#     health:
#       show-components: always
#       show-details: always
#   endpoints:
#     web:
#       exposure:
#         include: "health"
#   health:
#     defaults.enabled: false
#     ping.enabled: true
#     db.enabled: true
#     myhealth.enabled: true
