
---
spring:
  config.activate.on-profile: default
cds:
  datasource:
    auto-config.enabled: false
# server:
#   port: 8080
# spring:
#   config.activate.on-profile: cloud
# logging:
#   level:
#     '[com.sap.cds.auditlog]': DEBUG
#   web.resources.static-locations: "file:./app"
#   jmx:
#     enabled: true
# cds:
#   datasource:
#     auto-config.enabled: false
#   odata-v4.endpoint.path: "/api"
#   security.mock.users:
#     - name: admin
#       password: admin
#       roles:
#       - admin
#       attributes:
#         businessPartner:
#         - "10401010"
#     - name: user
#       password: user
# server.servlet.encoding:
#   charset: UTF-8
#   force: true
# management:
#   endpoint:
#     health:
#       show-components: always
#       show-details: always
#   endpoints:
#     web:
#       exposure:
#         include: "health"
#   health:
#     defaults.enabled: false
#     ping.enabled: true
#     db.enabled: true
#     myhealth.enabled: true